[toolchain]
anchor_version = "0.31.1"
solana_version = "4.1.0-beta.2"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
novaforge = "GiQ6ov39xDr4HrU1gM9kVJ82e9cVJh5xYMZ8qNtsxMP9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
