[toolchain]
anchor_version = "1.1.2"
solana_version = "2.1.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
novaforge = "5N4YA8DXFT2zuYWo627An8AN3Lx9eE5vQZV8v4LCCRWb"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
