[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
novaforge = "Dc5YsYCwHU5fMQb7Fz4qEWpnfSQLY25yLtRrDh1qaKon"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
