'use client'
import{useState}from'react'
import{PlanetType,Rarity,PLANET_COLORS,RARITY_COLORS}from'@/lib/types'
import{ActionStatus}from'@/lib/hooks/useAnchorActions'
import PlanetCanvas from'./PlanetCanvas'
import{X,Pickaxe,Orbit,FlaskConical,Zap,Shield,Sparkles}from'lucide-react'
interface Props{onClose:()=>void;onMint:(t:string,r:string)=>void;minting:boolean;mintStatus:ActionStatus;mintError?:string|null}
const TYPES:PlanetType[]=['Mining','Energy','Luxury','Research','Military'];const DESC:Record<PlanetType,string>={Mining:'HIGH IRON OUTPUT · ROCK GOLEM THREAT',Luxury:'HIGH GOLD OUTPUT · PIRATE INCURSIONS',Research:'LOWER UPGRADE COST · SWARM THREAT',Energy:'HIGH URANIUM OUTPUT · PLASMA THREAT',Military:'MAX DEFENSE · VOID TITAN THREAT'};const RARITIES:Rarity[]=['Common','Rare','Epic','Legendary'];const MULT:Record<Rarity,string>={Common:'1×',Rare:'2×',Epic:'3×',Legendary:'5×'};const ICON:Record<PlanetType,any>={Mining:Pickaxe,Energy:Zap,Luxury:Sparkles,Research:FlaskConical,Military:Shield}
export default function MintModal({onClose,onMint,minting,mintStatus,mintError}:Props){const[selType,setSelType]=useState<PlanetType>('Mining');const[selRarity,setSelRarity]=useState<Rarity>('Common');const col=PLANET_COLORS[selType],rc=RARITY_COLORS[selRarity],success=mintStatus==='success';const I=ICON[selType];return <div className="nf-modal-backdrop"><div className="nf-mint-modal"><div className="nf-modal-topline" style={{background:`linear-gradient(90deg,transparent,${col.primary},#fff,${col.primary},transparent)`}}/><header className="nf-modal-header"><div><div className="nf-kicker">GENESIS FORGE // MPL-CORE</div><h2>DEPLOY NEW WORLD</h2></div><button className="nf-icon-btn" onClick={onClose}><X size={17}/></button></header><div className="nf-mint-stage"><div className="nf-mint-planet"><div className="nf-mint-grid"/><PlanetCanvas planetType={selType} rarity={selRarity} size={170} hasRing={selType==='Military'||selRarity==='Legendary'}/><div className="nf-mint-readout"><span>TYPE</span><b>{selType}</b><span>RARITY</span><b style={{color:rc}}>{selRarity}</b></div></div><div className="nf-mint-copy"><div className="nf-mint-type"><I size={16}/><span>{selType}</span></div><h3>CHOOSE YOUR WEAPON</h3><p>{DESC[selType]}</p><div className="nf-mint-effect"><span>CORE MULTIPLIER</span><strong>{MULT[selRarity]}</strong></div></div></div><div className="nf-selector"><div className="nf-selector-title">PLANET ARCHETYPE</div><div className="nf-type-grid">{TYPES.map(t=>{const C=ICON[t],active=t===selType;return <button key={t} className={`nf-type-btn ${active?'active':''}`} onClick={()=>setSelType(t)} style={{'--accent':PLANET_COLORS[t].primary} as React.CSSProperties}><C size={15}/><span>{t}</span><small>{t==='Mining'?'IRON':t==='Energy'?'URANIUM':t==='Luxury'?'GOLD':t==='Research'?'SCIENCE':'DEFENSE'}</small></button>})}</div><div className="nf-selector-title rarity">RARITY SIGNATURE</div><div className="nf-rarity-grid">{RARITIES.map(r=>{const active=r===selRarity;return <button key={r} className={`nf-rarity-btn ${active?'active':''}`} onClick={()=>setSelRarity(r)} style={{'--accent':RARITY_COLORS[r]} as React.CSSProperties}><b>{MULT[r]}</b><span>{r.toUpperCase()}</span></button>})}</div></div>{mintError&&<div className="nf-action-error">MINT FAILED // {mintError}</div>}{success&&<div className="nf-success-strip">GENESIS COMPLETE // PLANET ASSET CREATED</div>}<footer className="nf-modal-footer"><button className="nf-secondary-btn" onClick={onClose}>CANCEL</button><button className="nf-primary-giant" disabled={minting||success} onClick={()=>onMint(selType,selRarity)}>{minting?'SIGNING ON SOLANA…':success?'PLANET DEPLOYED':'FORGE PLANET NFT →'}</button></footer></div></div>}
